/**
 * Luca Hooks Extension for Pi
 *
 * Auto-generated by Luca Framework build pipeline.
 * Bridges Luca shell hooks to Pi lifecycle events.
 *
 * Source: src/hooks/ → compiled via `bun run build:all`
 * DO NOT EDIT — regenerate with `bun run build:all --force`
 */
import { execSync } from "child_process";

export default function lucaHooks(pi) {
  const cwd = process.cwd();

  // post-edit-format: Formatting...
  pi.on("tool_execution_end", async (event, ctx) => {
    if (!["edit", "write"].includes(event.toolName || "")) return;
    try {
      execSync(`sh "${cwd}/.pi/hooks/post-edit-format.sh"`, {
        input: JSON.stringify({ tool_input: { file_path: event.input?.file_path || "" } }),
        timeout: 10000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });

  // post-edit-typecheck: Type-checking...
  pi.on("tool_execution_end", async (event, ctx) => {
    if (!["edit", "write"].includes(event.toolName || "")) return;
    try {
      execSync(`sh "${cwd}/.pi/hooks/post-edit-typecheck.sh"`, {
        input: JSON.stringify({ tool_input: { file_path: event.input?.file_path || "" } }),
        timeout: 30000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });

  // pre-commit-gate: Running pre-commit checks...
  pi.on("tool_call", async (event, ctx) => {
    const toolName = event.toolName || "";
    const cmd = event.input?.command || "";
    if (!["bash"].includes(toolName)) return;
    if (!/\bgit\s+commit\b|bun\s+run\s+commit/.test(cmd)) return;
    try {
      execSync(`sh "${cwd}/.pi/hooks/pre-commit-gate.sh"`, {
        input: JSON.stringify({ tool_input: { command: event.input?.command || "" } }),
        timeout: 120000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
        return { block: true, reason: "pre-commit-gate: checks failed" };
    }
  });

  // pre-commit-drift-check: Checking output drift...
  pi.on("tool_call", async (event, ctx) => {
    const toolName = event.toolName || "";
    const cmd = event.input?.command || "";
    if (!["bash"].includes(toolName)) return;
    if (!/\bgit\s+commit\b|bun\s+run\s+commit/.test(cmd)) return;
    try {
      execSync(`sh "${cwd}/.pi/hooks/pre-commit-drift-check.sh"`, {
        input: JSON.stringify({ tool_input: { command: event.input?.command || "" } }),
        timeout: 60000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
        return { block: true, reason: "pre-commit-drift-check: checks failed" };
    }
  });

  // context-check-throttled: Checking context...
  pi.on("tool_execution_end", async (event, ctx) => {
    try {
      execSync(`sh "${cwd}/.pi/hooks/context-check-throttled.sh"`, {
        input: JSON.stringify({ tool_input: { file_path: event.input?.file_path || "" } }),
        timeout: 10000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });

  // snapshot-sync: Syncing STATE.md...
  pi.on("tool_execution_end", async (event, ctx) => {
    try {
      execSync(`sh "${cwd}/.pi/hooks/snapshot-sync.sh"`, {
        input: JSON.stringify({ tool_input: { file_path: event.input?.file_path || "" } }),
        timeout: 10000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });

  // context-monitor: Checking context usage...
  pi.on("session_shutdown", async (event, ctx) => {
    try {
      execSync(`sh "${cwd}/.pi/hooks/context-monitor.sh"`, {
        input: JSON.stringify({}),
        timeout: 5000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });

  // session-persist: Saving session state...
  pi.on("session_shutdown", async (event, ctx) => {
    try {
      execSync(`sh "${cwd}/.pi/hooks/session-persist.sh"`, {
        input: JSON.stringify({}),
        timeout: 10000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });

  // session-start: Initializing Luca...
  pi.on("session_start", async (event, ctx) => {
    try {
      execSync(`sh "${cwd}/.pi/hooks/session-start.sh"`, {
        input: JSON.stringify({}),
        timeout: 15000,
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
    }
  });
}
