// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  inputCostCents: __t.u64().name("input_cost_cents"),
  outputCostCents: __t.u64().name("output_cost_cents"),
  totalCostCents: __t.u64().name("total_cost_cents"),
  turnCount: __t.u64().name("turn_count"),
  timestamp: __t.u64(),
});
