// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventType: __t.string().name("event_type"),
  sessionId: __t.string().name("session_id"),
  agentName: __t.string().name("agent_name"),
  toolName: __t.string().name("tool_name"),
  filePath: __t.string().name("file_path"),
  durationMs: __t.u64().name("duration_ms"),
  eventData: __t.string().name("event_data"),
  timestamp: __t.u64(),
});
