// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ContextSnapshots = __t.object("ContextSnapshots", {
  id: __t.u64(),
  sessionId: __t.string(),
  contextPercent: __t.u64(),
  messageCount: __t.u64(),
  estimatedTokens: __t.u64(),
  phase: __t.string(),
  timestamp: __t.u64(),
});
export type ContextSnapshots = __Infer<typeof ContextSnapshots>;

export const CostTracking = __t.object("CostTracking", {
  sessionId: __t.string(),
  inputCostCents: __t.u64(),
  outputCostCents: __t.u64(),
  totalCostCents: __t.u64(),
  turnCount: __t.u64(),
  timestamp: __t.u64(),
});
export type CostTracking = __Infer<typeof CostTracking>;

export const DecisionLogs = __t.object("DecisionLogs", {
  id: __t.u64(),
  sessionId: __t.string(),
  decisionType: __t.string(),
  chosenApproach: __t.string(),
  alternativesJson: __t.string(),
  reasoning: __t.string(),
  timestamp: __t.u64(),
});
export type DecisionLogs = __Infer<typeof DecisionLogs>;

export const HarnessResults = __t.object("HarnessResults", {
  id: __t.u64(),
  passed: __t.bool(),
  totalErrors: __t.u64(),
  totalWarnings: __t.u64(),
  checksJson: __t.string(),
  timestamp: __t.u64(),
});
export type HarnessResults = __Infer<typeof HarnessResults>;

export const IterationRecords = __t.object("IterationRecords", {
  id: __t.u64(),
  sessionId: __t.string(),
  tag: __t.string(),
  iteration: __t.u64(),
  errorCount: __t.u64(),
  errorDelta: __t.i64(),
  staleCount: __t.u64(),
  convergenceStatus: __t.string(),
  checkpointJson: __t.string(),
  timestamp: __t.u64(),
});
export type IterationRecords = __Infer<typeof IterationRecords>;

export const LedgerEntries = __t.object("LedgerEntries", {
  id: __t.u64(),
  sessionId: __t.string(),
  phase: __t.string(),
  plan: __t.string(),
  action: __t.string(),
  result: __t.string(),
  timestamp: __t.u64(),
  detailsJson: __t.string(),
  sequenceNumber: __t.u64(),
});
export type LedgerEntries = __Infer<typeof LedgerEntries>;

export const MemoryFiles = __t.object("MemoryFiles", {
  id: __t.u64(),
  brainJson: __t.string(),
  memoryJson: __t.string(),
  workingJson: __t.string(),
  proceduresJson: __t.string(),
  timestamp: __t.u64(),
});
export type MemoryFiles = __Infer<typeof MemoryFiles>;

export const Metrics = __t.object("Metrics", {
  id: __t.u64(),
  metricsJson: __t.string(),
  timestamp: __t.u64(),
});
export type Metrics = __Infer<typeof Metrics>;

export const Notes = __t.object("Notes", {
  id: __t.u64(),
  filename: __t.string(),
  body: __t.string(),
  priority: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
  consumedAt: __t.option(__t.u64()),
});
export type Notes = __Infer<typeof Notes>;

export const ObserverEvents = __t.object("ObserverEvents", {
  id: __t.u64(),
  eventType: __t.string(),
  sessionId: __t.string(),
  agentName: __t.string(),
  toolName: __t.string(),
  filePath: __t.string(),
  durationMs: __t.u64(),
  eventData: __t.string(),
  timestamp: __t.u64(),
});
export type ObserverEvents = __Infer<typeof ObserverEvents>;

export const SessionPlans = __t.object("SessionPlans", {
  id: __t.u64(),
  planJson: __t.string(),
  timestamp: __t.u64(),
});
export type SessionPlans = __Infer<typeof SessionPlans>;

export const Sessions = __t.object("Sessions", {
  sessionId: __t.string(),
  status: __t.string(),
  startTime: __t.u64(),
  lastEventTime: __t.u64(),
  eventCount: __t.u64(),
  complexity: __t.string(),
  ticketId: __t.string(),
});
export type Sessions = __Infer<typeof Sessions>;

export const SuspendCheckpoints = __t.object("SuspendCheckpoints", {
  id: __t.u64(),
  phaseId: __t.string(),
  checkpointJson: __t.string(),
});
export type SuspendCheckpoints = __Infer<typeof SuspendCheckpoints>;

export const TokenUsage = __t.object("TokenUsage", {
  id: __t.u64(),
  sessionId: __t.string(),
  turnNumber: __t.u64(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cacheReadTokens: __t.u64(),
  cacheWriteTokens: __t.u64(),
  timestamp: __t.u64(),
});
export type TokenUsage = __Infer<typeof TokenUsage>;

export const ToolCalls = __t.object("ToolCalls", {
  id: __t.u64(),
  sessionId: __t.string(),
  toolName: __t.string(),
  durationMs: __t.u64(),
  inputSize: __t.u64(),
  outputSize: __t.u64(),
  turnNumber: __t.u64(),
  timestamp: __t.u64(),
});
export type ToolCalls = __Infer<typeof ToolCalls>;

export const TribunalResults = __t.object("TribunalResults", {
  id: __t.u64(),
  resultJson: __t.string(),
  timestamp: __t.u64(),
});
export type TribunalResults = __Infer<typeof TribunalResults>;

export const WorkflowConfig = __t.object("WorkflowConfig", {
  id: __t.u64(),
  configJson: __t.string(),
});
export type WorkflowConfig = __Infer<typeof WorkflowConfig>;

export const WorkflowState = __t.object("WorkflowState", {
  id: __t.u64(),
  workflowState: __t.string(),
  currentPhase: __t.string(),
  complexity: __t.string(),
  oversight: __t.string(),
  sessionId: __t.string(),
  ticketId: __t.string(),
  contextJson: __t.string(),
});
export type WorkflowState = __Infer<typeof WorkflowState>;

