// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  workflowState: __t.string().name("workflow_state"),
  currentPhase: __t.string().name("current_phase"),
  complexity: __t.string(),
  oversight: __t.string(),
  sessionId: __t.string().name("session_id"),
  ticketId: __t.string().name("ticket_id"),
  contextJson: __t.string().name("context_json"),
});
