// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  tag: __t.string(),
  iteration: __t.u64(),
  errorCount: __t.u64(),
  errorDelta: __t.i64(),
  staleCount: __t.u64(),
  convergenceStatus: __t.string(),
  checkpointJson: __t.string(),
  timestamp: __t.u64(),
};
