// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  eventType: __t.string(),
  sessionId: __t.string(),
  agentName: __t.string(),
  toolName: __t.string(),
  filePath: __t.string(),
  durationMs: __t.u64(),
  eventData: __t.string(),
  timestamp: __t.u64(),
};
