// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  tag: __t.string(),
  iteration: __t.u64(),
  errorCount: __t.u64().name("error_count"),
  errorDelta: __t.i64().name("error_delta"),
  staleCount: __t.u64().name("stale_count"),
  convergenceStatus: __t.string().name("convergence_status"),
  checkpointJson: __t.string().name("checkpoint_json"),
  timestamp: __t.u64(),
});
