// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  turnNumber: __t.u64(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cacheReadTokens: __t.u64(),
  cacheWriteTokens: __t.u64(),
  timestamp: __t.u64(),
};
