// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  status: __t.string(),
  startTime: __t.u64().name("start_time"),
  lastEventTime: __t.u64().name("last_event_time"),
  eventCount: __t.u64().name("event_count"),
  complexity: __t.string(),
  ticketId: __t.string().name("ticket_id"),
});
