// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  turnNumber: __t.u64().name("turn_number"),
  inputTokens: __t.u64().name("input_tokens"),
  outputTokens: __t.u64().name("output_tokens"),
  cacheReadTokens: __t.u64().name("cache_read_tokens"),
  cacheWriteTokens: __t.u64().name("cache_write_tokens"),
  timestamp: __t.u64(),
});
