import { z } from "zod";

/**
 * A hex-string fingerprint uniquely identifying an error across iterations.
 * Generated by hashing file:line:code:normalizedMessage.
 */
export const errorFingerprintSchema = z
  .string()
  .min(1)
  .describe("Hex fingerprint of an error");
export type ErrorFingerprint = z.infer<typeof errorFingerprintSchema>;

/**
 * Error classification levels for the rule-based classifier.
 *
 * - transient: Retry without context (may be intermittent, e.g., build, network)
 * - correctable: Retry with error context (test, type, lint failures)
 * - permanent: Skip and continue on remaining (unfixable by iteration)
 */
export const ERROR_CLASSES = ["transient", "correctable", "permanent"] as const;
export const errorClassSchema = z.enum(ERROR_CLASSES);
export type ErrorClass = z.infer<typeof errorClassSchema>;

/**
 * A harness error enriched with classification and iteration tracking.
 *
 * Uses snake_case for data schema compatibility.
 */
export const classifiedErrorSchema = z.object({
  /** Hex fingerprint of this error */
  fingerprint: errorFingerprintSchema,
  /** Which harness check produced this error (test, typecheck, lint, build) */
  source: z.string(),
  /** Rule-based classification */
  classification: errorClassSchema,
  /** How many iterations this fingerprint has appeared in */
  iterations_seen: z.number().int().nonnegative(),
  /** Original error message */
  message: z.string(),
  /** File path where the error occurred */
  file: z.string().optional(),
  /** Line number in the file */
  line: z.number().int().positive().optional(),
  /** Error code (e.g., TS2345, ESLint rule name) */
  code: z.string().optional(),
});
export type ClassifiedError = z.infer<typeof classifiedErrorSchema>;

/**
 * The three signals used for multi-signal convergence detection.
 *
 * - error_count_delta: Net change in active (non-permanent) error count
 * - fingerprint_overlap: Jaccard similarity of error fingerprint sets (0.0 = all new, 1.0 = identical)
 * - artifact_change_delta: Number of files changed between iterations (from git diff --stat)
 *
 * Uses snake_case for data schema compatibility.
 */
export const convergenceSignalsSchema = z.object({
  error_count_delta: z.number().int(),
  fingerprint_overlap: z.number().min(0).max(1),
  artifact_change_delta: z.number().int().nonnegative(),
});
export type ConvergenceSignals = z.infer<typeof convergenceSignalsSchema>;

/**
 * Overall convergence assessment for an iteration.
 *
 * - improved: Progress made (errors decreased, new fixes applied)
 * - stalled: No meaningful progress (2-of-3 signals show no change)
 * - regressed: Got worse (errors increased)
 */
export const CONVERGENCE_STATUSES = [
  "improved",
  "stalled",
  "regressed",
] as const;
export const convergenceStatusSchema = z.enum(CONVERGENCE_STATUSES);
export type ConvergenceStatus = z.infer<typeof convergenceStatusSchema>;

/**
 * Full convergence assessment including signals, status, and stale tracking.
 *
 * Uses snake_case for data schema compatibility.
 */
export const convergenceResultSchema = z.object({
  signals: convergenceSignalsSchema,
  status: convergenceStatusSchema,
  /** Number of consecutive stale iterations (resets on improvement) */
  consecutive_stale: z.number().int().nonnegative(),
  /** Whether the loop should halt due to convergence failure (2+ consecutive stale) */
  should_halt: z.boolean(),
});
export type ConvergenceResult = z.infer<typeof convergenceResultSchema>;

/**
 * The two loop types in the execution pipeline.
 *
 * - harness: Loop A -- mechanical failures (test, type, lint, build)
 * - verify: Loop B -- semantic gaps (verifier finds plan objectives not met)
 */
export const LOOP_TYPES = ["harness", "verify"] as const;
export const loopTypeSchema = z.enum(LOOP_TYPES);
export type LoopType = z.infer<typeof loopTypeSchema>;

/**
 * Metadata for a single iteration checkpoint.
 *
 * Written to .planning/checkpoints/<tag-name>.json.
 * Uses snake_case for data schema compatibility.
 */
export const iterationRecordSchema = z.object({
  /** Git tag name, e.g., "iter/17/harness/1" */
  tag: z.string(),
  /** Phase number */
  phase: z.number().int().positive(),
  /** Which loop this iteration belongs to */
  loop: loopTypeSchema,
  /** 1-based iteration number */
  iteration: z.number().int().positive(),

  /** Total error count this iteration (active only, excludes permanent) */
  error_count: z.number().int().nonnegative(),
  /** Change from previous iteration (negative = improved) */
  error_delta: z.number().int(),
  /** Fingerprints of all errors this iteration */
  error_fingerprints: z.array(errorFingerprintSchema),

  /** Convergence assessment */
  convergence_status: convergenceStatusSchema,
  /** Consecutive stale count at this checkpoint */
  stale_count: z.number().int().nonnegative(),

  /** Fingerprints of errors promoted to permanent */
  permanent_errors: z.array(errorFingerprintSchema),
  /** Fingerprints of correctable errors */
  correctable_errors: z.array(errorFingerprintSchema),
  /** Fingerprints of transient errors */
  transient_errors: z.array(errorFingerprintSchema),

  /** Number of files changed (git diff --stat) */
  artifacts_delta: z.number().int().nonnegative(),
  /** Git commit hash at this checkpoint */
  commit_hash: z.string(),

  /** Name of the agent invoked this iteration */
  agent_invoked: z.string(),
  /** Duration of this iteration in milliseconds */
  duration_ms: z.number().int().nonnegative(),
  /** ISO 8601 timestamp */
  timestamp: z.string(),
});
export type IterationRecord = z.infer<typeof iterationRecordSchema>;

/**
 * Complete history of iterations for a loop instance.
 *
 * Tracks all iteration records and the fingerprint-to-iteration-count ledger
 * used for promotion decisions.
 *
 * Uses snake_case for data schema compatibility.
 */
export const iterationHistorySchema = z.object({
  /** Phase number */
  phase: z.number().int().positive(),
  /** Loop type */
  loop: loopTypeSchema,
  /** Ordered list of iteration records */
  iterations: z.array(iterationRecordSchema),
  /** Map of fingerprint -> number of iterations it has appeared in */
  fingerprint_ledger: z.record(
    errorFingerprintSchema,
    z.number().int().positive(),
  ),
});
export type IterationHistory = z.infer<typeof iterationHistorySchema>;

/**
 * Budget status for iteration cost tracking.
 *
 * - under_budget: Safe to continue
 * - soft_stop: At or above 80% threshold, finish current iteration but don't start new one
 * - exceeded: Hard budget exceeded (max iterations hit)
 */
export const BUDGET_STATUSES = [
  "under_budget",
  "soft_stop",
  "exceeded",
] as const;
export const budgetStatusSchema = z.enum(BUDGET_STATUSES);
export type BudgetStatus = z.infer<typeof budgetStatusSchema>;

/**
 * Budget tracking state for an iteration loop.
 *
 * Uses iteration count as the primary cost proxy. Optional token
 * fields enable token-aware budget assessment when real token
 * counting is available (via js-tiktoken).
 *
 * Uses snake_case for data schema compatibility.
 */
export const budgetStateSchema = z.object({
  /** Maximum iterations allowed (from ComplexityGate) */
  max_iterations: z.number().int().positive(),
  /** Current iteration number (1-based) */
  current_iteration: z.number().int().nonnegative(),
  /** Soft stop threshold as percentage (default 80) */
  soft_stop_percent: z.number().min(0).max(100).default(80),
  /** Current budget status */
  status: budgetStatusSchema,
  /** Optional: maximum token budget for this loop */
  max_tokens: z.number().int().positive().optional(),
  /** Optional: tokens consumed so far in this loop */
  tokens_used: z.number().int().nonnegative().optional(),
});
export type BudgetState = z.infer<typeof budgetStateSchema>;

/**
 * Human-in-the-loop decision options.
 *
 * - continue: Proceed to next iteration
 * - rollback: Revert to previous checkpoint and retry
 * - abort: Stop the loop entirely, keep current state
 * - skip: Skip remaining iterations, proceed to next pipeline step
 */
export const HITL_DECISIONS = [
  "continue",
  "rollback",
  "abort",
  "skip",
] as const;
export const hitlDecisionSchema = z.enum(HITL_DECISIONS);
export type HITLDecision = z.infer<typeof hitlDecisionSchema>;

/**
 * Iteration loop mode.
 *
 * - afk: Autonomous -- loop runs to completion without pausing
 * - hitl: Human-in-the-loop -- pause after each iteration for human decision
 */
export const ITERATION_MODES = ["afk", "hitl"] as const;
export const iterationModeSchema = z.enum(ITERATION_MODES);
export type IterationMode = z.infer<typeof iterationModeSchema>;

/**
 * Configuration for an iteration loop instance.
 *
 * The orchestrator (phase-execute skill) constructs this from
 * ComplexityGate values and config.json iteration settings.
 *
 * Uses snake_case for data schema compatibility.
 */
export const loopConfigSchema = z.object({
  /** Which loop type this is */
  loop_type: loopTypeSchema,
  /** Phase number */
  phase: z.number().int().positive(),
  /** Maximum iterations from ComplexityGate */
  max_iterations: z.number().int().nonnegative(),
  /** Iteration mode (afk or hitl) */
  mode: iterationModeSchema,
  /** Soft stop budget percentage (default 80) */
  soft_stop_percent: z.number().min(0).max(100).default(80),
  /** Number of consecutive stale iterations before halting (default 2) */
  stale_threshold: z.number().int().positive().default(2),
  /** Number of unchanged iterations before promoting correctable to permanent (default 3) */
  promotion_threshold: z.number().int().positive().default(3),
});
export type LoopConfig = z.infer<typeof loopConfigSchema>;

/**
 * The reason a loop terminated.
 *
 * - all_passed: All checks passed (success)
 * - max_iterations: Hard iteration limit reached
 * - convergence_failure: Stale threshold exceeded
 * - budget_exhausted: Soft stop budget threshold hit
 * - user_abort: User chose Abort in HITL mode
 * - user_skip: User chose Skip in HITL mode
 */
export const LOOP_OUTCOMES = [
  "all_passed",
  "max_iterations",
  "convergence_failure",
  "budget_exhausted",
  "user_abort",
  "user_skip",
] as const;
export const loopOutcomeSchema = z.enum(LOOP_OUTCOMES);
export type LoopOutcome = z.infer<typeof loopOutcomeSchema>;

/**
 * Final result of an iteration loop, returned to the orchestrator.
 *
 * Uses snake_case for data schema compatibility.
 */
export const loopResultSchema = z.object({
  /** How the loop terminated */
  outcome: loopOutcomeSchema,
  /** Total iterations completed */
  iterations_completed: z.number().int().nonnegative(),
  /** The last iteration record (checkpoint state at termination) */
  final_record: iterationRecordSchema.optional(),
  /** Complete iteration history */
  history: iterationHistorySchema,
  /** Errors still active at loop termination */
  remaining_errors: z.array(classifiedErrorSchema),
  /** Errors promoted to permanent during the loop */
  permanent_errors: z.array(classifiedErrorSchema),
});
export type LoopResult = z.infer<typeof loopResultSchema>;

/**
 * Configuration section for iteration behavior in .planning/config.json.
 *
 * Uses snake_case for config file compatibility.
 */
export const iterationConfigSchema = z.object({
  /** Default iteration mode */
  default_mode: iterationModeSchema.default("afk"),
  /** Soft stop budget percentage */
  soft_stop_percent: z.number().min(0).max(100).default(80),
  /** Consecutive stale iterations before halting */
  stale_threshold: z.number().int().positive().default(2),
  /** Iterations before promoting correctable errors to permanent */
  promotion_threshold: z.number().int().positive().default(3),
});
export type IterationConfig = z.infer<typeof iterationConfigSchema>;
