import {
    ComplexityLevel,
    lucaStateSchema,
    stringifyError,
    type LucaState,
    type RoadmapPhase,
} from '@alecsibilia/luca-core'

import { z, type ToolDescriptor } from '../__schemas/write-surface.schemas.ts'
import { mutateState } from '../helpers/mutate-state.ts'
import {
    applyPhaseDirMoves,
    ensurePhaseDir,
    slugAt,
    writeRoadmapMd,
    type PhaseDirMove,
} from '../helpers/roadmap-phases.ts'

const inputSchema = z.object({
    name: z
        .string()
        .min(1)
        .describe(
            'Prose phase name. Slugified to <NN>-<kebab-case>; the name must contain at least one letter so the slug starts with a letter.'
        ),
    deps: z
        .array(z.string())
        .default([])
        .describe('Names of phases this one depends on.'),
    complexity: ComplexityLevel.optional().describe(
        'Optional complexity hint recorded on the roadmap entry.'
    ),
    after: z
        .number()
        .int()
        .min(0)
        .optional()
        .describe(
            'Insert after this 1-based phase number (0 = insert first). Omit to append. Inserting RENUMBERS every later phase and renames their .luca/phases/ directories.'
        ),
})

/**
 * Append (or insert) a single phase into `state.roadmap`, create its
 * `.luca/phases/<NN>-<slug>/` directory, and REGENERATE `.luca/roadmap.md`.
 *
 * Why this exists: before it, four skills (`note`, `phase-add`,
 * `milestone-gaps`, `milestone-new`) registered phases by shelling out to
 * `mkdir -p` and hand-editing `.luca/roadmap.md`. Both are contract
 * violations — a raw `mkdir` bypasses the `<NN>-<slug>` validator, and
 * `roadmap.md` is declared GENERATED by LUCA_DIR_CONTRACT. This verb owns
 * the deterministic half (next-integer computation, slugification,
 * validation, directory creation, roadmap.md regeneration) and returns
 * `{ nn, slug, dir }` so the LLM never picks a path — mirroring the `dir`
 * contract of `luca phase current`.
 *
 * INSERTION RENUMBERS. Decimal phase numbers are not an option: `PHASE_SLUG_RE`
 * rejects them, which is exactly what makes the `phase-insert` skill
 * structurally broken. An insert therefore shifts every later phase up by one
 * and renames its directory, and `currentPhase` follows the phase it pointed
 * at so an in-flight run keeps the same active phase.
 *
 * Deliberately PHASE-AGNOSTIC (no `allowedPhases`, and `[]` in
 * WRITE_COMMAND_PHASES): phases get added mid-run — that is the entire point
 * of `/note` and `/phase-add` — so any non-empty restriction would make the
 * verb unreachable where it is used. Unlike `roadmap create` it cannot clobber
 * an in-progress roadmap: it only appends/inserts, never replaces, and refuses
 * any insert that would collide with an existing phase slug.
 *
 * Ordering note: state is written first (under the state lock), then the
 * filesystem is reconciled. If the fs step fails, the roadmap in state.json is
 * already correct and re-running any roadmap verb re-renders roadmap.md — the
 * inverse ordering would leave orphaned directories with no roadmap entry.
 */
export const lucaRoadmapAddPhaseTool: ToolDescriptor<
    z.infer<typeof inputSchema>
> = {
    name: 'luca_roadmap_add_phase',
    description:
        'Append or insert one phase into the roadmap in .luca/state.json, create its .luca/phases/<NN>-<slug>/ directory, and regenerate .luca/roadmap.md. Returns { nn, slug, dir }. Inserting renumbers later phases and renames their directories. Callable in every pipelineStep.',
    inputSchema,
    async handler(args, ctx) {
        // Populated inside the (synchronous) mutator so the filesystem
        // reconciliation below knows exactly what state decided.
        let plan:
            | {
                  nn: string
                  slug: string
                  moves: PhaseDirMove[]
              }
            | undefined
        let nextState: LucaState

        try {
            nextState = await mutateState(
                ctx.cwd,
                (state) => {
                    const insertIndex = args.after ?? state.roadmap.length
                    if (insertIndex > state.roadmap.length) {
                        throw new Error(
                            `--after ${args.after} is out of range: the roadmap has ${state.roadmap.length} phase(s), so --after must be 0..${state.roadmap.length}.`
                        )
                    }

                    const entry: RoadmapPhase = {
                        name: args.name,
                        deps: args.deps,
                        status: 'pending',
                        ...(args.complexity !== undefined
                            ? { complexity: args.complexity }
                            : {}),
                    }
                    const roadmap: RoadmapPhase[] = [
                        ...state.roadmap.slice(0, insertIndex),
                        entry,
                        ...state.roadmap.slice(insertIndex),
                    ]

                    // Validate the NEW entry's slug before anything is
                    // persisted — an unslugifiable name must not land in the
                    // roadmap and produce an out-of-contract phase directory.
                    const added = slugAt(state, roadmap, insertIndex + 1)
                    if (!added.ok) throw new Error(added.error)

                    // Renumbering moves: every phase after the insertion point
                    // shifts up one. Applied highest-first so a rename never
                    // lands on an occupied destination.
                    const moves: PhaseDirMove[] = []
                    for (let j = roadmap.length - 1; j > insertIndex; j -= 1) {
                        const from = slugAt(state, state.roadmap, j)
                        const to = slugAt(state, roadmap, j + 1)
                        // An entry whose name never slugified has no legal
                        // directory to move; skip rather than fail the insert.
                        if (!from.ok || !to.ok) continue
                        moves.push({ from: from.slug, to: to.slug })
                    }

                    // No slug-collision check is needed here: every slug is
                    // `<NN>-<kebab>` where NN is the roadmap INDEX, so two
                    // entries can never derive the same slug even with
                    // identical names. `applyPhaseDirMoves` still refuses a
                    // rename onto an existing directory, which covers the only
                    // real collision case (a stale out-of-contract directory).

                    // currentPhase follows the phase it pointed at: an insert
                    // at or before it shifts it up so the active phase does not
                    // silently change identity mid-run. A first phase on an
                    // empty roadmap activates, mirroring `roadmap create`.
                    let currentPhase = state.currentPhase
                    if (currentPhase === 0) {
                        currentPhase = roadmap.length > 0 ? 1 : 0
                    } else if (currentPhase >= insertIndex + 1) {
                        currentPhase += 1
                    }

                    plan = { nn: added.NN, slug: added.slug, moves }

                    return {
                        ...state,
                        roadmap,
                        totalPhases: roadmap.length,
                        currentPhase,
                    }
                },
                { bootstrapIfMissing: lucaStateSchema.parse({}) }
            )
        } catch (err) {
            return {
                content: [{ type: 'text', text: stringifyError(err) }],
                isError: true,
            }
        }

        if (!plan) {
            return {
                content: [
                    {
                        type: 'text',
                        text: 'internal error: roadmap add-phase produced no plan',
                    },
                ],
                isError: true,
            }
        }

        let renamed: PhaseDirMove[]
        let dir: string
        try {
            renamed = await applyPhaseDirMoves(ctx.cwd, plan.moves)
            dir = await ensurePhaseDir(ctx.cwd, plan.slug)
            await writeRoadmapMd(ctx.cwd, nextState)
        } catch (err) {
            return {
                content: [
                    {
                        type: 'text',
                        text: `roadmap updated in .luca/state.json, but the filesystem reconciliation failed — ${stringifyError(
                            err
                        )}`,
                    },
                ],
                isError: true,
            }
        }

        return {
            content: [
                {
                    type: 'text',
                    text: JSON.stringify(
                        {
                            nn: plan.nn,
                            slug: plan.slug,
                            dir,
                            totalPhases: nextState.totalPhases,
                            currentPhase: nextState.currentPhase,
                            renamed,
                        },
                        null,
                        2
                    ),
                },
            ],
        }
    },
}
