// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendIterationRecordReducer from "../append_iteration_record_reducer";
import AppendLedgerEntryReducer from "../append_ledger_entry_reducer";
import CompleteNoteReducer from "../complete_note_reducer";
import CreateNoteReducer from "../create_note_reducer";
import ExportToJsonReducer from "../export_to_json_reducer";
import ExportToMdReducer from "../export_to_md_reducer";
import IngestEventReducer from "../ingest_event_reducer";
import LogDecisionReducer from "../log_decision_reducer";
import LogTokenUsageReducer from "../log_token_usage_reducer";
import LogToolCallReducer from "../log_tool_call_reducer";
import SnapshotContextReducer from "../snapshot_context_reducer";
import UpdateCostReducer from "../update_cost_reducer";
import UpdateHarnessResultReducer from "../update_harness_result_reducer";
import UpdateMemoryFilesReducer from "../update_memory_files_reducer";
import UpdateMetricsReducer from "../update_metrics_reducer";
import UpdateSessionPlanReducer from "../update_session_plan_reducer";
import UpdateTribunalResultReducer from "../update_tribunal_result_reducer";
import UpdateWorkflowStateReducer from "../update_workflow_state_reducer";

export type AppendIterationRecordParams = __Infer<typeof AppendIterationRecordReducer>;
export type AppendLedgerEntryParams = __Infer<typeof AppendLedgerEntryReducer>;
export type CompleteNoteParams = __Infer<typeof CompleteNoteReducer>;
export type CreateNoteParams = __Infer<typeof CreateNoteReducer>;
export type ExportToJsonParams = __Infer<typeof ExportToJsonReducer>;
export type ExportToMdParams = __Infer<typeof ExportToMdReducer>;
export type IngestEventParams = __Infer<typeof IngestEventReducer>;
export type LogDecisionParams = __Infer<typeof LogDecisionReducer>;
export type LogTokenUsageParams = __Infer<typeof LogTokenUsageReducer>;
export type LogToolCallParams = __Infer<typeof LogToolCallReducer>;
export type SnapshotContextParams = __Infer<typeof SnapshotContextReducer>;
export type UpdateCostParams = __Infer<typeof UpdateCostReducer>;
export type UpdateHarnessResultParams = __Infer<typeof UpdateHarnessResultReducer>;
export type UpdateMemoryFilesParams = __Infer<typeof UpdateMemoryFilesReducer>;
export type UpdateMetricsParams = __Infer<typeof UpdateMetricsReducer>;
export type UpdateSessionPlanParams = __Infer<typeof UpdateSessionPlanReducer>;
export type UpdateTribunalResultParams = __Infer<typeof UpdateTribunalResultReducer>;
export type UpdateWorkflowStateParams = __Infer<typeof UpdateWorkflowStateReducer>;

