/**
 * Tests for Pi extension generation from hook registry.
 *
 * Validates that generatePiExtension() produces a valid TypeScript
 * extension that bridges Luca hooks to Pi lifecycle events.
 */
import { describe, test, expect } from "bun:test";
import { generatePiExtension } from "~/hooks/__helpers/config-generators";
import { resolveHookRegistry } from "~/hooks/__helpers/hook-registry";
import type { HookDefinition } from "~/hooks/__schemas/hook.schemas";

describe("generatePiExtension", () => {
  const registry = resolveHookRegistry();

  test("generates valid TypeScript module with default export", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain("export default function lucaHooks(pi)");
    expect(ext).toContain('import { execSync } from "child_process"');
  });

  test("includes auto-generated header comment", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain("Luca Hooks Extension for Pi");
    expect(ext).toContain("Auto-generated by Luca Framework");
    expect(ext).toContain("DO NOT EDIT");
  });

  test("maps PostToolUse hooks to tool_execution_end", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain('pi.on("tool_execution_end"');
    // post-edit-format and post-edit-typecheck
    expect(ext).toContain("post-edit-format.sh");
    expect(ext).toContain("post-edit-typecheck.sh");
  });

  test("maps PreToolUse hooks to tool_call with block return", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain('pi.on("tool_call"');
    expect(ext).toContain("pre-commit-gate.sh");
    expect(ext).toContain("{ block: true, reason:");
  });

  test("maps SessionStart to session_start", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain('pi.on("session_start"');
    expect(ext).toContain("session-start.sh");
  });

  test("maps SessionEnd and Stop to session_shutdown", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain('pi.on("session_shutdown"');
    expect(ext).toContain("session-persist.sh");
    expect(ext).toContain("context-monitor.sh");
  });

  test("applies tool name filtering for edit/write hooks", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain('["edit", "write"]');
  });

  test("applies commit command filtering for pre-commit hooks", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain("git\\s+commit");
    expect(ext).toContain("bun\\s+run\\s+commit");
  });

  test("uses correct timeout values from registry", () => {
    const ext = generatePiExtension(registry);
    // pre-commit-gate: 120s = 120000ms
    expect(ext).toContain("timeout: 120000");
    // post-edit-format: 10s = 10000ms
    expect(ext).toContain("timeout: 10000");
    // post-edit-typecheck: 30s = 30000ms
    expect(ext).toContain("timeout: 30000");
  });

  test("skips hooks without piEvent", () => {
    const partial: Record<string, HookDefinition> = {
      "has-pi": {
        event: "PostToolUse",
        cursorEvent: "afterFileEdit",
        piEvent: "tool_execution_end",
        script: "has-pi.sh",
        timeout: 10,
        async: false,
      },
      "no-pi": {
        event: "PostToolUse",
        cursorEvent: "afterFileEdit",
        piEvent: undefined,
        script: "no-pi.sh",
        timeout: 10,
        async: false,
      },
    };
    const ext = generatePiExtension(partial);
    expect(ext).toContain("has-pi.sh");
    expect(ext).not.toContain("no-pi.sh");
  });

  test("uses custom hooksDir when provided", () => {
    const ext = generatePiExtension(registry, { hooksDir: "custom/hooks" });
    expect(ext).toContain("custom/hooks/");
    expect(ext).not.toContain(".pi/hook-scripts/");
  });

  test("passes stdin JSON for tool_execution_end hooks", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain("file_path: event.input?.file_path");
  });

  test("passes stdin JSON for tool_call hooks", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain("command: event.input?.command");
  });

  test("passes empty JSON for session hooks", () => {
    const ext = generatePiExtension(registry);
    expect(ext).toContain("JSON.stringify({})");
  });

  test("generates handler for every hook with piEvent", () => {
    const ext = generatePiExtension(registry);
    const hooksWithPiEvent = Object.entries(registry).filter(
      ([, def]) => def.piEvent,
    );
    for (const [, def] of hooksWithPiEvent) {
      expect(ext).toContain(def.script);
    }
  });
});

describe("hook registry Pi event mappings", () => {
  const registry = resolveHookRegistry();

  test("all hooks have piEvent defined", () => {
    for (const [name, def] of Object.entries(registry)) {
      expect(def.piEvent).toBeDefined();
      expect(typeof def.piEvent).toBe("string");
    }
  });

  test("PostToolUse hooks map to tool_execution_end", () => {
    const postToolUseHooks = Object.entries(registry).filter(
      ([, def]) => def.event === "PostToolUse",
    );
    for (const [, def] of postToolUseHooks) {
      expect(def.piEvent).toBe("tool_execution_end");
    }
  });

  test("PreToolUse hooks map to tool_call", () => {
    const preToolUseHooks = Object.entries(registry).filter(
      ([, def]) => def.event === "PreToolUse",
    );
    for (const [, def] of preToolUseHooks) {
      expect(def.piEvent).toBe("tool_call");
    }
  });

  test("SessionStart maps to session_start", () => {
    const sessionStartHooks = Object.entries(registry).filter(
      ([, def]) => def.event === "SessionStart",
    );
    for (const [, def] of sessionStartHooks) {
      expect(def.piEvent).toBe("session_start");
    }
  });

  test("SessionEnd and Stop map to session_shutdown", () => {
    const endHooks = Object.entries(registry).filter(
      ([, def]) => def.event === "SessionEnd" || def.event === "Stop",
    );
    for (const [, def] of endHooks) {
      expect(def.piEvent).toBe("session_shutdown");
    }
  });

  test("edit/write hooks have piMatcher with edit and write", () => {
    const editHooks = Object.entries(registry).filter(
      ([, def]) => def.matcher === "Edit|Write",
    );
    for (const [, def] of editHooks) {
      expect(def.piMatcher).toContain("edit");
      expect(def.piMatcher).toContain("write");
    }
  });

  test("pre-commit hooks have piMatcher with bash", () => {
    const preCommitHooks = Object.entries(registry).filter(
      ([, def]) => def.event === "PreToolUse" && def.matcher === "Bash",
    );
    for (const [, def] of preCommitHooks) {
      expect(def.piMatcher).toContain("bash");
    }
  });
});
