import { existsSync } from 'node:fs'
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

export interface WireClaudeHooksOptions {
    cwd: string
    log?: (msg: string) => void
}

// Matcher per decision:luca-stage-gate-hook-scope-2026-05-19 (D2): hook fires
// on every tool that can mutate the filesystem.
const STAGE_GATE_MATCHER = 'Edit|Write|NotebookEdit|Bash'

const STAGE_GATE_SCRIPT = `#!/usr/bin/env bash
# Generated by \`luca init\`. Delegates to the luca CLI for stage-gate
# enforcement. The CLI handles the PreToolUse contract — parsing stdin,
# applying the phase→tool matrix, and exiting non-zero to block.
exec luca hook stage-gate
`

const STAGE_GATE_COMMAND = '"$CLAUDE_PROJECT_DIR"/.claude/hooks/stage-gate.sh'

interface HookEntry {
    type: 'command'
    command: string
    timeout?: number
    statusMessage?: string
}

interface PreToolUseEntry {
    matcher: string
    hooks: HookEntry[]
}

interface ClaudeSettings {
    hooks?: {
        PreToolUse?: PreToolUseEntry[]
        [k: string]: unknown
    }
    [k: string]: unknown
}

/**
 * Wire Claude Code stage-gate hook registration in the project's .claude/
 * directory. Creates .claude/hooks/stage-gate.sh and merges the PreToolUse
 * entry into .claude/settings.json without clobbering existing config.
 *
 * Idempotent — re-running won't duplicate the hook entry.
 */
export async function wireClaudeHooks(
    opts: WireClaudeHooksOptions
): Promise<void> {
    const log = opts.log ?? (() => {})
    const claudeDir = join(opts.cwd, '.claude')
    const hooksDir = join(claudeDir, 'hooks')
    const hookPath = join(hooksDir, 'stage-gate.sh')
    const settingsPath = join(claudeDir, 'settings.json')

    await mkdir(hooksDir, { recursive: true })

    // 1. Write the hook wrapper script (always overwrites — it's generated).
    await writeFile(hookPath, STAGE_GATE_SCRIPT)
    await chmod(hookPath, 0o755)
    log(`  write: ${hookPath}`)

    // 2. Read existing settings.json (if any) and merge.
    const existing = existsSync(settingsPath)
        ? ((JSON.parse(
              await readFile(settingsPath, 'utf-8')
          ) as ClaudeSettings) ?? {})
        : {}

    const next = mergeStageGateRegistration(existing)

    await writeFile(settingsPath, JSON.stringify(next, null, 2) + '\n')
    log(`  write: ${settingsPath}`)
}

/**
 * Merge the stage-gate PreToolUse registration into an existing
 * ClaudeSettings object. If an entry referencing stage-gate.sh already
 * exists anywhere under PreToolUse, this is a no-op (idempotent).
 *
 * Pure function — exported for testability.
 */
export function mergeStageGateRegistration(
    settings: ClaudeSettings
): ClaudeSettings {
    const next: ClaudeSettings = { ...settings }
    next.hooks = { ...(settings.hooks ?? {}) }
    const preToolUse = [...(next.hooks.PreToolUse ?? [])]

    // Idempotency: if any existing entry already references stage-gate.sh,
    // leave the settings untouched.
    const alreadyRegistered = preToolUse.some((entry) =>
        entry.hooks?.some((h) => h.command?.includes('stage-gate.sh'))
    )
    if (alreadyRegistered) {
        next.hooks.PreToolUse = preToolUse
        return next
    }

    preToolUse.push({
        matcher: STAGE_GATE_MATCHER,
        hooks: [
            {
                type: 'command',
                command: STAGE_GATE_COMMAND,
                timeout: 30,
            },
        ],
    })

    next.hooks.PreToolUse = preToolUse
    return next
}
