// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  decisionType: __t.string().name("decision_type"),
  chosenApproach: __t.string().name("chosen_approach"),
  alternativesJson: __t.string().name("alternatives_json"),
  reasoning: __t.string(),
  timestamp: __t.u64(),
});
