// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  toolName: __t.string().name("tool_name"),
  durationMs: __t.u64().name("duration_ms"),
  inputSize: __t.u64().name("input_size"),
  outputSize: __t.u64().name("output_size"),
  turnNumber: __t.u64().name("turn_number"),
  timestamp: __t.u64(),
});
