// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workflowState: __t.string(),
  currentPhase: __t.string(),
  complexity: __t.string(),
  oversight: __t.string(),
  sessionId: __t.string(),
  ticketId: __t.string(),
  contextJson: __t.string(),
};
